fmod STRING-LIST is
    protecting LIST{String} * (sort NeList{String} to NeStringList ,
                             sort List{String} to StringList ) + INT .
    op mts : -> String [ctor] . 

    op _[_] : StringList Int -> String .

    var S : String . 
    var SL : StringList .
    var N : Int . 

    eq tail(nil) = nil .
    eq head(nil) = nil .

    eq SL [ N ] = if N <= 0 then if N == 0 then head(SL) else nil fi else tail(SL) [ N - 1 ] fi .

    
endfm